version: "3.7"
services:
  db:
    image: postgres:13-alpine
    container_name: house_media_postgres
    restart: always
    env_file: .env.local
    ports:
      - 5433:5432/tcp
    volumes:
      - house_media_postgres:/var/lib/postgresql/data
volumes:
  house_media_postgres:
    name: house_media_postgres
    driver: local
